### ISSUE TITLE
"unsupported file type/types" for sprite animation atlas when trying to import

### ISSUE THREAD

**Issue by kutoman** [UnderwaterApps/overlap2d#153] opened 2015-08-05 19:29 UTC
as far as I know this should be supported, right?
http://www.file-upload.net/download-10820969/circleTimerAnimation.zip.html

**Comment by azakhary** [comment] 2015-08-05 19:33
no, this is a wrong atlas file, all regions gave same name if you look inside

**Comment by kutoman** [comment] 2015-08-05 20:15
hmm I see, libgdx's texture packer produced that. How would I create a proper atlas instead?

**Comment by azakhary** [comment] 2015-08-05 20:47
it's because you had underlines or dashes in file names not sure which one was big nono for libgdx texture packer.

**Comment by kutoman** [comment] 2015-08-05 22:02
ah right, I remember. When using underlines with numbers, the files are mapped to the same region name but having different indices. Afaik libgdx makes use of it in asset managing or something alike

**Comment by kutoman** [comment] 2015-08-05 22:10
the import mechanism could also make use of that imho

**Comment by kutoman** [comment] 2015-08-06 11:11
ok this time I imported the animation without an atlas. The tiles are named "circletimerXXXX". The import succeeds, but overlap2d crashes as soon as I put the animation on canvas.

log:
```
Processing image for circletimer0062: x[623] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0063: x[623] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0064: x[2] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0065: x[2] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0066: x[209] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0067: x[2] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0068: x[209] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0069: x[416] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0070: x[2] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0071: x[209] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0072: x[416] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0073: x[623] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0074: x[209] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0075: x[416] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0076: x[623] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0077: x[416] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0078: x[623] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0079: x[623] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0080: x[2] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0081: x[2] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0082: x[209] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0083: x[2] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0084: x[209] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0085: x[416] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0086: x[2] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0087: x[209] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0088: x[416] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0089: x[623] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0090: x[209] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0091: x[416] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0092: x[623] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0093: x[416] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0094: x[623] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0095: x[623] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0096: x[2] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0097: x[2] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0000: x[2] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0001: x[2] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0002: x[209] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0003: x[2] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0004: x[209] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0005: x[416] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0006: x[2] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0007: x[209] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0008: x[416] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0009: x[623] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0010: x[209] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0011: x[416] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0012: x[623] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0013: x[416] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0014: x[623] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0015: x[623] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0016: x[2] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0017: x[2] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0018: x[209] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0019: x[2] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0020: x[209] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0021: x[416] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0022: x[2] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0023: x[209] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0024: x[416] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0025: x[623] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0026: x[209] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0027: x[416] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0028: x[623] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0029: x[416] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0030: x[623] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0031: x[623] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0032: x[2] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0033: x[2] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0034: x[209] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0035: x[2] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0036: x[209] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0037: x[416] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0038: x[2] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0039: x[209] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0040: x[416] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0041: x[623] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0042: x[209] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0043: x[416] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0044: x[623] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0045: x[416] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0046: x[623] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0047: x[623] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0048: x[2] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0049: x[2] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0050: x[209] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0051: x[2] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0052: x[209] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0053: x[416] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0054: x[2] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0055: x[209] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0056: x[416] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0057: x[623] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0058: x[209] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0059: x[416] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0060: x[623] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0061: x[416] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0062: x[623] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0063: x[623] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0064: x[2] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0065: x[2] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0066: x[209] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0067: x[2] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0068: x[209] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0069: x[416] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0070: x[2] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0071: x[209] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0072: x[416] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0073: x[623] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0074: x[209] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0075: x[416] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0076: x[623] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0077: x[416] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0078: x[623] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0079: x[623] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0080: x[2] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0081: x[2] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0082: x[209] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0083: x[2] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0084: x[209] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0085: x[416] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0086: x[2] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0087: x[209] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0088: x[416] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0089: x[623] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0090: x[209] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0091: x[416] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0092: x[623] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0093: x[416] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0094: x[623] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0095: x[623] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0096: x[2] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0097: x[2] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0000: x[2] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0001: x[2] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0002: x[209] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0003: x[2] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0004: x[209] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0005: x[416] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0006: x[2] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0007: x[209] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0008: x[416] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0009: x[623] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0010: x[209] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0011: x[416] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0012: x[623] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0013: x[416] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0014: x[623] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0015: x[623] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0016: x[2] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0017: x[2] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0018: x[209] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0019: x[2] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0020: x[209] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0021: x[416] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0022: x[2] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0023: x[209] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0024: x[416] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0025: x[623] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0026: x[209] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0027: x[416] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0028: x[623] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0029: x[416] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0030: x[623] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0031: x[623] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0032: x[2] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0033: x[2] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0034: x[209] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0035: x[2] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0036: x[209] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0037: x[416] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0038: x[2] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0039: x[209] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0040: x[416] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0041: x[623] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0042: x[209] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0043: x[416] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0044: x[623] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0045: x[416] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0046: x[623] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0047: x[623] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0048: x[2] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0049: x[2] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0050: x[209] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0051: x[2] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0052: x[209] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0053: x[416] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0054: x[2] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0055: x[209] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0056: x[416] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0057: x[623] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0058: x[209] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0059: x[416] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0060: x[623] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0061: x[416] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0062: x[623] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0063: x[623] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0064: x[2] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0065: x[2] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0066: x[209] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0067: x[2] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0068: x[209] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0069: x[416] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0070: x[2] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0071: x[209] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0072: x[416] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0073: x[623] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0074: x[209] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0075: x[416] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0076: x[623] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0077: x[416] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0078: x[623] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0079: x[623] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0080: x[2] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0081: x[2] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0082: x[209] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0083: x[2] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0084: x[209] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0085: x[416] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0086: x[2] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0087: x[209] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0088: x[416] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0089: x[623] y[623] w[205] h[205], rotate[false]
Processing image for circletimer0090: x[209] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0091: x[416] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0092: x[623] y[416] w[205] h[205], rotate[false]
Processing image for circletimer0093: x[416] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0094: x[623] y[209] w[205] h[205], rotate[false]
Processing image for circletimer0095: x[623] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0096: x[2] y[2] w[205] h[205], rotate[false]
Processing image for circletimer0097: x[2] y[2] w[205] h[205], rotate[false]
java.lang.ArrayIndexOutOfBoundsException: -1
        at com.uwsoft.editor.renderer.components.sprite.SpriteAnimationStateComponent.sortAndGetRegions(SpriteAnimationS
tateComponent.java:42)
        at com.uwsoft.editor.renderer.components.sprite.SpriteAnimationStateComponent.<init>(SpriteAnimationStateCompone
nt.java:18)
        at com.uwsoft.editor.renderer.factory.component.SpriteComponentFactory.createSpriteAnimationDataComponent(Sprite
ComponentFactory.java:100)
        at com.uwsoft.editor.renderer.factory.component.SpriteComponentFactory.createComponents(SpriteComponentFactory.j
ava:58)
        at com.uwsoft.editor.renderer.factory.EntityFactory.createEntity(EntityFactory.java:150)
        at com.uwsoft.editor.factory.ItemFactory.createSpriteAnimation(ItemFactory.java:116)
        at com.uwsoft.editor.view.ui.box.resourcespanel.UIAnimationsTabMediator$$Lambda$45/189200141.apply(Unknown Sourc
e)
        at com.uwsoft.editor.view.ui.box.resourcespanel.draggable.DraggableResource.drop(DraggableResource.java:86)
        at com.uwsoft.editor.view.ui.box.resourcespanel.draggable.DraggableResource.access$100(DraggableResource.java:36
)
        at com.uwsoft.editor.view.ui.box.resourcespanel.draggable.DraggableResource$2.drop(DraggableResource.java:76)
        at com.badlogic.gdx.scenes.scene2d.utils.DragAndDrop$1.dragStop(DragAndDrop.java:134)
        at com.badlogic.gdx.scenes.scene2d.utils.DragListener.touchUp(DragListener.java:64)
        at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:58)
        at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:348)
        at com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:96)
        at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:306)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:234)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessControPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: No OpenGL context found in the current thread.
        at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
        at org.lwjgl.opengl.GL11.glDeleteTextures(GL11.java:732)
        at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glDeleteTexture(LwjglGL20.java:248)
        at com.badlogic.gdx.graphics.GLTexture.delete(GLTexture.java:170)
        at com.badlogic.gdx.graphics.Texture.dispose(Texture.java:194)
        at com.badlogic.gdx.graphics.g2d.TextureAtlas.dispose(TextureAtlas.java:418)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin.dispose(Skin.java:389)
        at com.kotcrab.vis.ui.VisUI.dispose(VisUI.java:65)
        at com.uwsoft.editor.Overlap2D.dispose(Overlap2D.java:92)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$4.run(LwjglCanvas.java:309)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by azakhary** [comment] 2015-08-06 11:27
Can I have the new file to test?

**Comment by kutoman** [comment] 2015-08-06 11:59
here you are:
http://www.filedropper.com/timeranimation

**Comment by azakhary** [comment] 2015-08-06 12:25
Issue was in the runtime, already pushed fixed index sorting. Thanks for finding!
You can download latest jar it should support your animation

**Closed** 2015-08-06 12:25 UTC

**Comment by easymodo** [comment] 2016-01-09 22:25
Hi,
I have noticed that .atlas import fails whenever i mix region names with and without numbers in the same file..
For example: 

> player1.png
size: 1024,128
format: RGBA8888
filter: Nearest,Nearest
repeat: none
**pwalk01**
  rotate: false
  xy: 2, 2
  size: 72, 97
  orig: 72, 97
  offset: 0, 0
  index: -1
**pwalk02**
  rotate: false
  xy: 76, 2
  size: 72, 97
  orig: 72, 97
  offset: 0, 0
  index: -1

Imports fine.
But if i for example add this to the end, import will fail:

>**pstanding**
>  rotate: false
>  xy: 150, 2
  size: 72, 97
  orig: 72, 97
  offset: 0, 0
  index: -1

Is this an actual error or i should just not bother and put numbered frames in separate atlas?

**Comment by azakhary** [comment] 2016-01-11 08:40
I think that's a bad behavior on our import side. It makes sense to open issue with reproducing steps.
