### ISSUE TITLE
Cannot Delete Resolution

### ISSUE THREAD

**Issue by johanessurya** [UnderwaterApps/overlap2d#236] opened 2015-09-05 18:01 UTC
I try to change resolution but can't. So I add one and want to delete the old one, but I can't. 

It show dialog box to choose 'Delete' or 'Cancel'. When I click delete. Nothing happen. I tried in other resolution but still can't. I try add new one. So I have 3 resolution and delete it, but can't.

**Comment by azakhary** [comment] 2015-09-06 14:41
Also adding link t forum post
 http://overlap2d.com/forums/topic/i-cannot-delete-resolution/

**Comment by saltares** [comment] 2015-10-25 21:08
I think this could be a duplicate of #252.

**Comment by azakhary** [comment] 2015-10-26 10:48
Yep that's a duplicate, (or rather the other one is). as issue is fixed in #283 PR, I am closing this. And the other one as well, as resolved.

**Closed by azakhary** 2015-10-26 10:48 UTC
