### ISSUE TITLE
[Bug] Add light to image/texture/asset via CompositeItem

### ISSUE THREAD

**Issue by Honguito98** [UnderwaterApps/overlap2d#28] opened 2015-04-07 04:40 UTC
Physic data 'must be' saved in a composite item, if it's saved physic data in compositeItem/image, there are bugs with lights or physics.

![img2](https://cloud.githubusercontent.com/assets/11828802/7017008/41298b0e-dcb6-11e4-88a6-7ede89b2976f.png)
![img3](https://cloud.githubusercontent.com/assets/11828802/7017011/4cfb067e-dcb6-11e4-8991-5894b0e74131.png)

**Comment by azakhary** [comment] 2015-04-07 09:03
I have added physics to an image from assets list, then put it on scene and converted into composite, but lights still work as they should, could you please share the exact steps? Sorry about that.

**Comment by Honguito98** [comment] 2015-04-07 16:36
**Missing gear:**
1. Open the project.
2. Put a gear (or ball) from assets with stored physics.
3. Add a light, then select this and the gear, I do right click and select Group into composite.
4. Save the project
5. Export settings.
6. Result: the gear does not show, just the light

**Unoriented image:**
(follow the first three steps)...
4. Modify the physics for the composite item (just right click on the created gear)
5. Set the mesh and body type to dynamic.
6. Save physic data.
7. Save project, export settings.
8. Result: light does works (it moves, falls),  but gear does some weird actions.

**Correct physics:**
(follow the first three steps from 'Missing gear')..
4. Edit the composite item, delete the physics for 'image', then save physics.
5. Exit from composite item editing, then save project and expor settings.
6. Result: does works! Gear and light will falls by gravity. :sunglasses:

**Comment by azakhary** [comment] 2015-07-17 13:52
Completely redesign physics system should have this fixed since #75. But I am not closing till we check and make sure.

**Comment by azakhary** [comment] 2015-07-27 13:16
This doesnot apply anymore. Might have other manifestation, but would have to have new ways to reproduce now, so I am closing this one.

**Closed by azakhary** 2015-07-27 13:16 UTC
