### ISSUE TITLE
[bug] click the composite crashed!

### ISSUE THREAD

**Issue by tianqiujie** [UnderwaterApps/overlap2d#235] opened 2015-09-05 06:00 UTC
I add dialogLayer in MainScene. and add a image in dialogLayer ,  and convert it to composite, and double click it, and then click the image of the composite, the editor crashed. error is:

➜  overlap2d  java -jar /Users/tian/Documents/work/overlap2d/overlap2D-0.1.1.jar 
VisUI: Warning, using default favorites preference name for file chooser! (see FileChooser.setFavoritesPrefsName(String))
VisUI: Warning, using default favorites preference name for file chooser! (see FileChooser.setFavoritesPrefsName(String))
java.lang.NullPointerException
	at com.uwsoft.editor.view.stage.tools.SelectionTool.isEntityVisible(SelectionTool.java:357)
	at com.uwsoft.editor.view.stage.tools.SelectionTool.itemMouseDown(SelectionTool.java:143)
	at com.uwsoft.editor.view.stage.SandboxMediator$SandboxItemEventListener.touchDown(SandboxMediator.java:210)
	at com.uwsoft.editor.view.stage.input.SandboxInputAdapter.touchDown(SandboxInputAdapter.java:105)
	at com.badlogic.gdx.InputMultiplexer.touchDown(InputMultiplexer.java:90)
	at com.badlogic.gdx.backends.jglfw.JglfwInput$1.touchDown(JglfwInput.java:87)
	at com.badlogic.gdx.InputProcessorQueue.drain(InputProcessorQueue.java:77)
	at com.badlogic.gdx.backends.jglfw.JglfwInput.update(JglfwInput.java:138)
	at com.badlogic.gdx.backends.jglfw.JglfwApplication.frame(JglfwApplication.java:212)
	at com.badlogic.gdx.backends.jglfw.JglfwApplication.start(JglfwApplication.java:197)
	at com.badlogic.gdx.backends.jglfw.JglfwApplication.initialize(JglfwApplication.java:177)
	at com.badlogic.gdx.backends.jglfw.JglfwApplication$1.run(JglfwApplication.java:87)
	at java.lang.Thread.run(Thread.java:745)
➜  overlap2d

**Comment by azakhary** [comment] 2015-09-05 06:16
I am on it.

**Comment by azakhary** [comment] 2015-09-05 06:21
That's weird I am unable to reproduce, can you confirm that you are doing it with the editor that was downloaded from the website in near 3-4 days?

**Comment by tianqiujie** [comment] 2015-09-05 06:23
2015年8月23日 上午1:51

2015-09-05 14:21 GMT+08:00 Avetis <notifications@github.com>:

**Comment by azakhary** [comment] 2015-09-05 06:26
Could be old one, please re-download to be sure. and try on empty project.
I create empty project, import one image to it. Add new layer, add that image to that  layer, convert into composite, then double click to go inside, and click on image, and nothing bad happens.

**Comment by azakhary** [comment] 2015-09-05 06:27
If it works for you on empty project, but still crashes on the old project. then try to delete all other elements on the scene and leave only that composite that crashes. then send me that ".dt" file for scene, so I can reproduce.

**Comment by tianqiujie** [comment] 2015-09-05 06:31
OK, i have try the new editor version. It works for me on empty,  but still
crashes on my project.

And the composite is named "dialog"

2015-09-05 14:27 GMT+08:00 Avetis <notifications@github.com>:

**Comment by azakhary** [comment] 2015-09-05 06:37
you can try re-creating your dialog. it will probably fix the problem. But if you want me to take a look. please attach he dt file, with as few other elements as possible.

**Comment by tianqiujie** [comment] 2015-09-05 06:40
OK, here is my project

2015-09-05 14:37 GMT+08:00 Avetis <notifications@github.com>:

**Comment by azakhary** [comment] 2015-09-05 06:44
I don't think you can attach it from email, you have to do it from github :)

**Comment by azakhary** [comment] 2015-09-05 06:44
Also, btw, the transparency of composite elements had issue, it has been fixed, so if you will do that one, make sure you have latest editor/runtime

**Comment by tianqiujie** [comment] 2015-09-05 06:47
OK, I have fix it. I don't know why the MenuScene.dt was save error.
 "uniqueId":23,
                "itemIdentifier":"dialog",
                "tags":[

                ],
                "originX":0,
                "originY":0,
                "zIndex":14,
                "layerName":"dialogLayer",
                "composite":{
                    "sImages":[
                        {
                            "uniqueId":22,
                            "itemIdentifier":"dialogBg",
                            "tags":[

                            ],
                            "scaleX":0.89830506,
                            "scaleY":0.89830506,
                            "originX":0,
                            "originY":0,
                            "layerName":"dialogLayer",
                            "imageName":"giftsmall"
                        },
                        {
                            "uniqueId":5,
                            "tags":[

                            ],
                            "x":93,
                            "y":90,
                            "scaleX":0.8669202,
                            "scaleY":0.8669202,
                            "originX":0,
                            "originY":0,
                            "zIndex":1,
                            "layerName":"Default",
                            "imageName":"giftbuy1"
                        }
                    ],
                    "layers":[
                        {
                            "layerName":"Default",
                            "isVisible":true
                        }
                    ]

But the gitfsmall image's layerName should be "Default", and I change the
"dialogLayer" to "Default" whitch itemIdentifier named "dialogBg"

2015-09-05 14:44 GMT+08:00 Avetis <notifications@github.com>:

**Comment by azakhary** [comment] 2015-09-05 06:53
Got it. The only thing that worries me is: was it the old editor that saves the wrong data, or will new editor too save wrong data if reproduced correctly..

**Comment by azakhary** [comment] 2015-09-07 11:46
I think it might have been related also to layer renaming at some point. which is fixed. Let's close it for now, if it happens again with new editor. Then we'll get back to it

**Closed by azakhary** 2015-09-07 11:46 UTC
